src/main/java/com/mango/diary/common/exception/BaseException.java, src/main/java/com/mango/diary/common/exception/ErrorCode.java, src/main/java/com/mango/diary/common/exception/GlobalExceptionHandler.java, src/main/java/com/mango/diary/common/exception/dto/ErrorResponse.java
- 전역 예외 처리기 구현
- 전역 예외 처리기 구현
- ErrorResponse DTO 추가
- ErrorCode 인터페이스 추가
- BaseException 클래스 추가
=> Feat/#10 exception handler : 전역 예외 처리기 구현

.gitignore, build.gradle, src/main/java/com/mango/diary/MangoDiaryApplication.java, src/main/resources/application.yml
- 환경변수 세팅
- application.yml env 로 대체
- dotenv 설정
- .gitignore 수정
=> Feat/#16 env : 환경변수 세팅

src/main/java/com/mango/diary/common/enums/Emotion.java, src/main/java/com/mango/diary/diary/controller/DiaryController.java, src/main/java/com/mango/diary/diary/domain/AiComment.java, src/main/java/com/mango/diary/diary/domain/Diary.java, src/main/java/com/mango/diary/diary/dto/DiaryRequest.java, src/main/java/com/mango/diary/diary/dto/DiaryResponse.java, src/main/java/com/mango/diary/diary/exception/DiaryErrorCode.java, src/main/java/com/mango/diary/diary/exception/DiaryException.java, src/main/java/com/mango/diary/diary/repository/AiCommentRepository.java, src/main/java/com/mango/diary/diary/repository/DiaryRepository.java, src/main/java/com/mango/diary/diary/service/DiaryService.java
- 일기 crd 기본 기능 구현 
- 일기 작성/조회/삭제 기본 기능 api 구현
- DiaryEntity, DiaryRepository 구현
- AiCommentEntity, AiCommentRepository 구현
- Diary exception 구현
=> Feat/#4 diary crd : 일기 crd 기본 기능 구현 

src/main/java/com/mango/diary/auth/config/AuthConfig.java, src/main/java/com/mango/diary/common/enums/Emotion.java, src/main/java/com/mango/diary/diary/controller/DiaryController.java, src/main/java/com/mango/diary/diary/domain/AiComment.java, src/main/java/com/mango/diary/diary/domain/Diary.java, src/main/java/com/mango/diary/diary/dto/DiaryRequest.java, src/main/java/com/mango/diary/diary/dto/DiaryResponse.java, src/main/java/com/mango/diary/diary/exception/DiaryErrorCode.java, src/main/java/com/mango/diary/diary/repository/AiCommentRepository.java, src/main/java/com/mango/diary/diary/service/DiaryService.java
피드백에 맞게 수정 완료 
- emotion 감정 한글로 수정
- @AuthUser 사용
- 일기 삭제 message 반영
- CASCADE 반영
- LAZY LODING 반영
-
=> Feat/#20 accept feadback 

src/main/java/com/mango/diary/auth/controller/AuthController.java, src/main/java/com/mango/diary/diary/controller/AiCommentController.java, src/main/java/com/mango/diary/diary/controller/DiaryController.java, src/main/java/com/mango/diary/diary/domain/Diary.java, src/main/java/com/mango/diary/diary/dto/AiCommentRequest.java, src/main/java/com/mango/diary/diary/dto/AiEmotionRequest.java, src/main/java/com/mango/diary/diary/dto/AiEmotionResponse.java, src/main/java/com/mango/diary/diary/dto/DiaryRequest.java, src/main/java/com/mango/diary/diary/dto/GeminiRequest.java, src/main/java/com/mango/diary/diary/dto/GeminiResponse.java, src/main/java/com/mango/diary/diary/exception/DiaryErrorCode.java, src/main/java/com/mango/diary/diary/service/DiaryService.java, src/main/java/com/mango/diary/diary/service/GeminiService.java
- Ai 기능과 일기 작성 기능 분리
- Ai 기능과 일기 작성 기능을 분리
- Ai 관련 기능인 감정 분석과, comment  기능 분리하여 엔드포인트 추가
- 감정 분석 기능 예외처리
- 감정 분석을 할수 없는 일기가 입력되면 예외 발생
=> Feat/#26 ai fix : Ai 기능과 일기 작성 기능 분리

src/main/java/com/mango/diary/diary/controller/DiaryController.java, src/main/java/com/mango/diary/diary/dto/DiaryListDTO.java, src/main/java/com/mango/diary/diary/repository/DiaryRepository.java, src/main/java/com/mango/diary/diary/service/DiaryService.java
- 일기 검색 기능 구현
- DiaryListDTO 생성
- 일기 검색 엔드포인트 추가
- 일기 검색 로직 구현
- 페이지네이션 가능하게 검색 기능 구현함
=> Feat/#28 diary search: 일기 검색 기능 구현

.github/workflows/deploy.yml
=> [hotfix]: deploy.yml 오타 수정

src/main/java/com/mango/diary/common/config/SwaggerConfig.java
=> [hotfix]: 자동배포 테스트

src/main/java/com/mango/diary/diary/service/GeminiService.java
=> [feat]: Gemini prompt 관련 코드 수정

docker-compose.yml
=> [feat]: docker-compose에 portainer 설정 적용

src/main/java/com/mango/diary/auth/config/AuthConfig.java, src/main/java/com/mango/diary/diary/service/DiaryService.java, src/main/java/com/mango/diary/diary/service/GeminiService.java, src/main/java/com/mango/diary/statistics/controller/StatisticsController.java, src/main/java/com/mango/diary/statistics/dto/StatisticsResponse.java, src/main/java/com/mango/diary/statistics/entity/EmotionStatistics.java, src/main/java/com/mango/diary/statistics/exception/StatisticsErrorCode.java, src/main/java/com/mango/diary/statistics/exception/StatisticsException.java, src/main/java/com/mango/diary/statistics/repository/StatisticsRepository.java, src/main/java/com/mango/diary/statistics/service/StatisticsService.java, src/main/resources/application.yml
- 통계 기능 구현
- 통계 기능 관련 Entity, Repository, Service, Exception 구현
- 통계에 들어가는 ai 커멘트 생성하는 프롬프트 추가 및 기능 구현
=> Feat/#36 statistics: 통계 기능 구현

src/main/resources/application.yml
=> [hotfix]: db create 로 변경

docker-compose.yml, src/main/resources/application.yml
=> merge to main

src/main/java/com/mango/diary/auth/domain/KakaoUser.java, src/main/java/com/mango/diary/auth/domain/OAuthUser.java, src/main/java/com/mango/diary/auth/oauth/RestTemplateOAuthRequester.java, src/main/java/com/mango/diary/auth/service/OAuthService.java, src/main/resources/application.yml
- 카카오 로그인시 닉네임 설정 오류 해결
-  카카오 로그인시 닉네임 설정 오류 해결
=> Fix/#52 oauth 카카오 로그인시 닉네임 설정 오류 해결

.github/workflows/deploy.yml
=> [hotfix]: deploy.yml 수정

.github/workflows/deploy.yml
=> [hotfix]: deploy.yml 웹훅 제거

.github/workflows/deploy.yml
=> [hotfix]: deploy.yml 배포 코드 추가

.github/workflows/deploy.yml
=> [hotfix]: IP 수정

.github/workflows/deploy.yml
=> [hotfix]: deploy.yml 최종 수정

src/main/java/com/mango/diary/diary/controller/DiaryController.java
- 감정별 일기 리스트 조회와 전체 리스트 조회 api 통합
- 감정별 일기 리스트 조회와 전체 리스트 조회 api 통합
=> [feat]: 감정별 일기 리스트 조회와 전체 리스트 조회 api 통합

src/main/java/com/mango/diary/diary/controller/DiaryController.java, src/main/java/com/mango/diary/diary/exception/DiaryErrorCode.java, src/main/java/com/mango/diary/diary/service/DiaryService.java
=> Feat/#75 diary month list: 다이어리 부분 리펙토링

src/main/java/com/mango/diary/diary/service/DiaryService.java, src/main/java/com/mango/diary/statistics/dto/StatisticsResponse.java, src/main/java/com/mango/diary/statistics/service/StatisticsService.java
=> [hotfix]: statistics 기능 수정

src/main/java/com/mango/diary/diary/controller/DiaryController.java, src/main/java/com/mango/diary/diary/dto/DiaryIdRequest.java, src/main/java/com/mango/diary/diary/repository/DiaryRepository.java, src/main/java/com/mango/diary/diary/service/DiaryService.java, src/main/java/com/mango/diary/statistics/entity/EmotionStatistics.java
=> [hotfix]: 일기 삭제 기능 수정 배포

src/main/java/com/mango/diary/auth/jwt/JwtProvider.java, src/main/java/com/mango/diary/diary/controller/DiaryController.java, src/main/java/com/mango/diary/diary/dto/DiaryIdDTO.java, src/main/java/com/mango/diary/diary/exception/DiaryErrorCode.java, src/main/java/com/mango/diary/diary/service/DiaryService.java, src/main/java/com/mango/diary/diary/service/GeminiService.java
- Gemini 예외처리
- 엑세스 토큰 기간 12시간 설정
- 일기 생성리 리턴으로 id 값 보냄
=> [hotfix]: 오류사항 수정
